### ISSUE TITLE
How to return an object synchronously?

### ISSUE THREAD

**Issue by leosdad** [josephtzeng/hocon-parser#19]
Hi,

I wonder if there is some way to parse a conf file synchronously. For example, in a project (written in Typescript) I have a class called Parsers with this method:
```ts
public static parseObject(contents: string, ext: string): any
  {
    switch(ext) {
      case '.json':
        return JSON.parse(contents);
      case '.jsonc':
      case '.hjson':
      case '.schema':
        return Hjson.parse(contents);
      case '.conf':
        return this.parseHocon(contents);  // Still pending
      case '.scss':
        return this.parseScss(contents);
      default:
        throw new Error(`Builder: Format '${ext}' not recognized`);
    }
  }
```
It is used as a way to read configuration files. It must return immediately so as the program can proceed. However after many hours of tweaking, researching and testing I cannot figure a way to do it. Is that possible at all? Thanks in advance.

**Comment by josephtzeng** [comment]
Hi,

It's not possible to make the parsing synchronous without a rewrite. It's designed this way so node resolution, transform invocation, and source loading can all be async.
