### ISSUE TITLE
Including files still doesn't work on Windows

### ISSUE THREAD

**Issue by lemmingucwcz** [josephtzeng/hocon-parser#22]
Hello!

I recently posted issue #21 You provided a fix, but including on Windows still doesn't work with the same error. 

I have submerged into the code and found what's the problem:

In `lib/core/Context.js` there is class `ContextUrl`, which handles URLs. This class has method `join(path)`.

That method is called from `FileSource::appendPath()` method when a file is included using a relative path.

The `ContextUrl::join()` method calls `no_path.join()`, which is a Node.JS library function. This join() function normalizes the path. On Windows, this converts all the slashes **("/")** in the path to backslashes **("\\")** in the process!

So when `ContextUrl::toString()` method is called to finally format the URL, the input (in this.$) is like:

```
{
        protocol: 'file:',
        slashes: true,
        auth: '',
        host: '',
        port: '',
        hostname: '',
        hash: '',
        search: '',
        query: '',
        pathname: '\\C:\\Users\\Michal\\IdeaProjects\\hocon-parser\\tests\\resources\\configs\\simple-include\\included',
        path: '/C:/Users/Michal/IdeaProjects/hocon-parser/tests/resources/configs/simple-include/test.conf',
        href: 'file:///C:/Users/Michal/IdeaProjects/hocon-parser/tests/resources/configs/simple-include/test.conf',
        source: 'file'
}
```

Notice backslashes in the pathname (they are doubled, because they are escaped).

URL is formatted by calling `no_url.format()` function (standard Node.JS function) and it doesn't work well with this mix of slashes and backslashes and produces `file:////C:/Users/Michal/IdeaProjects/hocon-parser/tests/resources/configs/simple-include/test.conf`, which is not a correct URL (because of the four slashes after `file:`).

It seems there is no option to alter this behavior of Node.JS functions. So the only fix I found is to convert backslashes to slashes on Windows after joining the path. I did it in the `ContextUrl::join()` function, so it looks like that:

```
    join (path)
    {
        this.$.pathname = no_path.join (this.$.pathname, path);
        if (WINDOWS && this.$.pathname.startsWith('\\')) {
            this.$.pathname = this.$.pathname.replace('\\', '/')
        }
    }

```

It works now, but it is not a nice fix, IMO. Since it is very simple, I have not created a pull request.

So please have a look at this. If you have any questions, feel free to ask!
Regards.

**Comment by lemmingucwcz** [comment]
On last master `npm run test` my result is:

`Test Suites: 3 failed, 52 passed, 55 total
Tests:       26 failed, 718 passed, 744 total
Snapshots:   0 total
Time:        6.834 s
Ran all test suites.
`

Including include tests that still fail with "File URL path must be absolute"

I get the same result with cmd, powershell and bash (git bash).

**Comment by josephtzeng** [comment]
Could you copy and paste the output of the failed tests? And what version of Windows and node were used?

**Comment by lemmingucwcz** [comment]
I am running Windows 10 (some current version). My node version is:

```
C:\Users\Michal\IdeaProjects\sophon>node -v
v16.17.0
```

I have attached `npm run test` output as a file:
[test_out.txt](https://github.com/josephtzeng/hocon-parser/files/9619515/test_out.txt)

**Comment by lemmingucwcz** [comment]
It seems like some of the failed tests are because GIT converted test files to CR LF. I will try to fix that and post updated output. But it should not affect the include problem.

**Comment by lemmingucwcz** [comment]
I checked out the project with correct line endings and now only tests with includes fail: 
[test_out2.txt](https://github.com/josephtzeng/hocon-parser/files/9619597/test_out2.txt)

**Comment by josephtzeng** [comment]
Yeah, it failed with node v16 and above. I've pushed another fix with url.parse ().pathname to normalize the path. It's been tested with v16 and v18. Please check if you get any errors.

**Comment by lemmingucwcz** [comment]
Splendid! Now all tests pass and with version 1.2.3 include in my original project is finally working. Thank you!

**Comment by josephtzeng** [comment]
Great! Thanks for the help on this issue.
