### ISSUE TITLE
Include takes the relative path of the reader rather than the file's path

### ISSUE THREAD

**Issue by Amgelo563** [josephtzeng/hocon-parser#34]
Hello, I'm having an issue when trying to parse an included file on a config on a nested folder with this setup:

### index.js
```js
const parse = require('@pushcorn/hocon-parser');
const fs = require('fs');

async function main() {
    const file = fs.readFileSync('config/test.conf', 'utf-8');
    console.log(await parse({
        text: file
    }))
};

main();
```
### config/test.conf
```hocon
{
    include "nest/included.conf"
}
```
### config/nest/included.conf
```hocon
expected = true
```
### Expected value when running `node index.js`:
```json
{ "expected": true }
```
### Actual value:
```json
{ }
```

---

While testing, I tried setting the path in `test.conf` to `config/nest/included.conf` and I got the expected value.

I think the parser is trying to parse the path relative to the "reader" (so in the not working case it would be trying to parse `root/nest/included.conf` instead of `root/config/nest/included.conf`). Strangely the CLI seems to be working just fine, as I get the expected result without making any changes (just running `npm exec parse-hocon config/test.conf` from root).

I didn't see any documentation about relative paths so I'm asking here just in case. I'd appreciate any kind of help if maybe I missed some configuration option or something.

Thanks for the help!

**Comment by pushcorn** [comment]
Hello,

In the index file, you are passing the content of the config to the parser, so it'll just use the current directory as the parent directory. If you change the param to `{ url: "config/test.conf" }`, the parser will have the info of the loader path and the relative path will be resolved properly. That's why it works for the CLI.

**Comment by Amgelo563** [comment]
That did the work, thanks!
